# Gradle Info
java_version=21
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
# Minecraft Info
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.152
neo_version_range=[21,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
# Mod Info
mod_id=skyland
mod_name=AnvilCraft-Skyland
mod_license=GNU LGPL 3.0
mod_version=1.0.1
mod_group_id=dev.anvilcraft.skyland
mod_authors=Gugle
mod_description=A Mod about Skyland
# Dependencies Info
registrate_version=MC1.21-1.3.0+62
anvilcraft_version=1.5.0+build.1441
anvillib_version=1.4.0+build.160
rolling_gate_version=1.1.0+build.64
cloth_config_version=15.0.130
jei_version=19.19.0.219
curios_version=9.0.15+1.21.1
