# Gradle Info
java_version=21
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
# Minecraft Info
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.249
neo_version_range=[21,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
# Mod Info
mod_id=skyland
mod_name=AnvilCraft-Skyland
mod_license=GNU LGPL 3.0
mod_version=1.0.2
mod_group_id=dev.anvilcraft.skyland
mod_authors=Gugle, Meo_Lobster, Cjsah
mod_description=A Mod about Skyland
# Dependencies Info
anvilcraft_version=1.6.0+snapshot.2225
anvillib_version=2.0.0+snapshot.518
rolling_gate_version=1.1.0+build.66
cloth_config_version=15.0.140
jei_version=19.39.0.372
curios_version=9.0.15+1.21.1
